### PR TITLE
add typedef so other arduinos can use this library

### PR DESCRIPTION
**Pull request by ladyada**
float_t isnt a thing for most arduinos :)

### CODE REVIEW

**Review by cparata — CHANGES_REQUESTED** [review]
Maybe we can include this typedef in a block like:

#ifndef float_t

#endif

So it is safer.

**Comment by ladyada** [comment]
if float_t a #define or a typedef? if its a typedef you cannot test it it with #ifdef

https://stackoverflow.com/questions/6772802/in-c-c-is-there-a-directive-similar-to-ifndef-for-typedefs

**Comment by cparata** [comment]
Hi @ladyada ,
you are right. I replaced directly float_t with float in the code, so now it should be compatible also with other Arduino boards.
Best Regards,
Carlo

**Comment by fpistm** [comment]
Hi @ladyada 

The library.properties defines this library only compatible with stm32 arch. Which arch you used ?
Maybe it should be also updated with another arch tested ?

**Comment by ladyada** [comment]
we used with Arduino UNO / AVR, so it should probably work with any platform

**Comment by cparata** [comment]
Ok @ladyada ,
please let me know if v1.0.1 works also with Arduino UNO, so we can update the library properties adding also the avr platform.
Best Regards,
Carlo

**Comment by ladyada** [comment]
You should set the platform to * like this:
https://github.com/adafruit/Adafruit_MPU6050/blob/master/library.properties#L9
as this library isn't ST-specific and you'll want more than just ST micros to work  :)

**Comment by cparata** [comment]
Ok I updated the library properties and I added a new release.
I hope that now it is okay.
Best Regards,
Carlo

**Comment by ladyada** [comment]
thats great, i will have customers try it. they are really loving this sensor :) :) :)

**Pull request closed without merging**
